<Project Sdk="Microsoft.NET.Sdk">

    <!-- Mod Metadata -->
    <PropertyGroup>
        <Title>Fill My Bloomery</Title>
        <Description>Adds the ability to fully fill bloomeries in one click by holding control and shift when depositing. A recreation of "One Click Fill for Bloomery" by ArcadianPig.</Description>

        <Version>1.0.2</Version>

        <RepositoryUrl>https://github.com/Cecer/VS-FillMyBloomery/</RepositoryUrl>
        <PackageProjectUrl>https://mods.vintagestory.at/fillmybloomery</PackageProjectUrl>
    </PropertyGroup>

    <!-- Compile Configuration -->
    <PropertyGroup>
        <RootNamespace>FillMyBloomery</RootNamespace>
    </PropertyGroup>
</Project>
